### ISSUE TITLE
Goo type conversion bug

### ISSUE THREAD

**Issue by Entoarox** [MercuriusXeno/Goo#100]
When changing the type of the crystal at https://github.com/MercuriusXeno/Goo/blob/1.16.3/src/main/java/com/xeno/goo/tiles/GooBulbTile.java#L248, you are not updating what the `crystalFluid` is to match that of the crystal, this causes the most-abundant goo fluid to be converted into that of the pre-existing crystal's type, no matter what type that crystal actually is.

**Comment by MercuriusXeno** [comment]
Fixed in the dev build, hopefully. Leaving this tracked.

**Comment by MercuriusXeno** [comment]
No longer able to repro, think this one's good.
