### ISSUE TITLE
Is it normal that the FPS drops to a screeching halt every time I load a world?

### ISSUE THREAD

**Issue by Cynix32** [MercuriusXeno/Goo#122]
MC 1.16.5
Forge 36.2.2
GraalVM Java8

Everytime I load a world, the FPS drops to literal 0 for quite some time (it takes really long) before returning to normal. Looking at the console, somehow  aequivaleo and goo are trying to "scan" every single dimension present. It does not matter if the world is previously saved or is just a newly created worldJust wanna ask if this is normal behavior or is there something probably wrong?
This is an extremely large modpack 

Console logs (only showing the point where aequivaleo tries to scan every dimension):
https://gist.github.com/Cynix32/2a5750c055062106b396c4ef0010fc51

**Comment by MercuriusXeno** [comment]
You should report this in Aequivaleo's github. Goo doesn't scan anything.
