### ISSUE TITLE
Bulbs are too heckin small

### ISSUE THREAD

**Issue by MercuriusXeno** [MercuriusXeno/Goo#15]
Add more bulbs! 16 buckets is weirdly not enough space for some things (but it is for others)

Make some expansion recipes!

**Comment by MercuriusXeno** [comment]
Hey @Aemande123 this feature is in the next release.

You can upgrade a bulb to a bulb x8, to a bulb x64, to a bulb x512, to a bulb x4096.

I stopped at 4096 because that's a heckin lot of goo. It should be in the next beta :D

**Comment by Aemande123** [comment]
> Hey @Aemande123 this feature is in the next release.
> 
> You can upgrade a bulb to a bulb x8, to a bulb x64, to a bulb x512, to a bulb x4096.
> 
> I stopped at 4096 because that's a heckin lot of goo. It should be in the next beta :D

Wow, this is cool! :D
