### ISSUE TITLE
"Not Goo"

### ISSUE THREAD

**Issue by MLMII** [MercuriusXeno/Goo#22]
goo-1.16.1-0.5.7.1
Patchouli-1.16-39
aequivaleo-0.0.46-alpha
forge 32.0.108

When I start up a world in either survival or creative everything lists as "not goo" when I use the book in my off hand and the machines do not seem to accept any items or blocks to turn into goo.

Thanks

**Comment by MercuriusXeno** [comment]
I think we fixed this already, there was a bug in the tooltips but also unrelated bugs in Aequivaleo. I'll leave this open until we can confirm it on the next release.

But thanks for the heads up all the same

**Comment by MercuriusXeno** [comment]
This should be fixed!
