### ISSUE TITLE
Tooltip Woes 

### ISSUE THREAD

**Issue by Birgliss** [MercuriusXeno/Goo#24]
fair warning, this is using Goo 0.5.7.1, and some work seems to have been done since then, so i couldn't say if this happens in the current dev version

basically: tooltips on goo bulbs can get kinda.. weird. 
![2020-09-28_21 57 50](https://user-images.githubusercontent.com/20749209/94503968-b027eb00-01d5-11eb-85b6-123ded14d34d.png)
this is the setup i used to reproduce. i marked the bulb in question affected by the bug. 
![image](https://user-images.githubusercontent.com/20749209/94504101-0563fc80-01d6-11eb-914a-a6dcdf781a04.png)
for the first screenshot, i built the setup and then placed 1 cobblestone in the gooifier.
i suspect nbt shenanigans; something about not properly clearing tags after the goo pump empties the bulb.

if you use an item with a lower goo volume, like an iron ingot, the tooltip will be much smaller, but still feature a lot of dead space.

**Comment by MercuriusXeno** [comment]
Unsure, I think I noticed this issue during testing but it may or may not be fixed by quite a bit of drift. We'll check it again in a later build, leaving this open for now.

**Comment by MercuriusXeno** [comment]
I remembered what this was lol. The collection of fluids in a bulb is a LIST type and it can include empties, any number of them. Not only was their update call not respecting it but the handler responsible for tooltips wasn't either.

The behavior now is an auto-pruning and also tooltips don't show or allocate space for "empty" fluid stacks, which does correct this behavior.

I will STILL leave this open, as a formality, until we confirm it's good in a latest release.

**Comment by MercuriusXeno** [comment]
Should be fixed!
