### ISSUE TITLE
Goo and You not showing anything when in offhand

### ISSUE THREAD

**Issue by CoruscareGames** [MercuriusXeno/Goo#25]
Minecraft 1.16.1
Aequivaleo 0.0.46
Patchouli 1.16.1-1.1.0
Goo 0.5.7.1

When I have the book in the offhand, I'm not able to identify the goo of any items. I hover over the items in the inventory and they show what they normally show and nothing else.

If this is possibly from conflicts with other mods, I'm willing to send the list. Speaking of which, is there a way to give goo data to items from other mods?

**Comment by MercuriusXeno** [comment]
Should be fixed already but hold out for another release. A TON of work is going into the next build, which includes this and other fixes/changes.

**Comment by CoruscareGames** [comment]
Thanks a bunch. When's the expected release? It's part of a modpack I'm making and your mod seems very interesting, so I would love to play with it.

**Comment by MercuriusXeno** [comment]
I'm not sure yet - I'm working now on "splats" which are not nearly done yet, but well on their way as a mature system, with a few effects coded in and a basic framework. I expect I need a few days of contiguous work to wrap them up, and real life keeps getting in the way.

You're the second person approached about a pack, I'll do my best to make it happen soon. :D

**Comment by MercuriusXeno** [comment]
The patchouli book instructions are updated to clarify that you only need the book in your *inventory* now, it doesn't have to be in your off-hand, I found it to be very annoying to insist on that slot.
