### ISSUE TITLE
Exception in ToolTipHandler.java when looking at a Nitwit villager with Goo 0.5.7.1

### ISSUE THREAD

**Issue by Entoarox** [MercuriusXeno/Goo#28]
It completely hangs the game, I have to manually shut it down as it becomes completely unresponsive.
Log file: [latest.log](https://github.com/MercuriusXeno/Goo/files/5323567/latest.log)

Hope you can get this fixed ASAP Xeno, cause I love this way of handling equivalence in minecraft about 100 times as much as I did the EMC mechanic! 😄

**Comment by MercuriusXeno** [comment]
I'm trying to reproduce this but I'm not sure precisely what to do. I have a villager in front of me but it seems like nothing happens.

Is it possible we fixed this already?

Would you mind trying with our latest build? I just posted it today.

**Comment by Entoarox** [comment]
As of right now, it seems this has been fixed, so I am gonna close this. Thanks Xeno! 😄
