### ISSUE TITLE
Machines drop items in creative even when they aren't empty

### ISSUE THREAD

**Issue by jackhardwareltd** [MercuriusXeno/Goo#33]

**Comment by jackhardwareltd** [comment]
Probably related, crucibles, mixers, and gooifiers all drop as items when broken in creative, which they're not supposed to.

**Comment by MercuriusXeno** [comment]
No, it's intended. When I was testing in creative I needed things that contained goo to drop themselves for testing purposes, it was helpful for getting containers of the goo I was trying to test.

Pumps don't drop anything because they're always inherently empty.

**Comment by MercuriusXeno** [comment]
Also noteworthy, empty bulbs drop nothing. But now that

**Comment by MercuriusXeno** [comment]
Issue will be resolved in a later release (machines won't drop items unless they contain something)

Also it wasn't obvious that the gooifier does, in fact, contain goo.
So does the solidifier. I'll have to resolve this too, in the tooltips.

**Comment by MercuriusXeno** [comment]
Aaaaand now I see what the original issue was stating. Pumps don't drop anything outside of creative mode. Yeah, those two things aren't related and should have been a separate issue :D

**Comment by MercuriusXeno** [comment]
Now solidifiers and gooifiers clearly display their contents just like other goo containers so it's obvious 1) why they don't stack and 2) that they contain goo when broken in mid operation. It'll be in the next build.
