### ISSUE TITLE
Filters on pumps don't work correctly (with small amounts of goo?)

### ISSUE THREAD

**Issue by jackhardwareltd** [MercuriusXeno/Goo#34]
It's difficult to explain, so here's exactly what I did.

Inserted netherwart (Strange and Shroom goo) into gooifier with tank on side, placed crucible a block away.
Placed pump facing crucible. First issue is that the 'Strange' goo goes into the crucible, even though there's no recipe for Strange goo in a crucible. (Should I write a separate issue for this?)
Second issue is that once I placed a red mushroom (Shroom goo) into the pump, it continued to pull out the Strange, when it should have only pulled out the Shroom.

If I let the tank empty, then filled it with different goo (I did Luxury and Metal from gold) and then filled it with again with Strange, the Strange goo was no longer pulled out, and Shroom still was. I think that points towards some sort of timing issue to when the filter starts to apply.

**Comment by MercuriusXeno** [comment]
I trust this might be an indexing issue or something similar. I'll have to experiment with pumps in my playtest, but it sounds like a straightforward bug.

**Comment by MercuriusXeno** [comment]
Figured this one out; when proccing their filter, the pumps try to bypass the fluids that don't match the contents of their target, but then use the wrong method of fluid handler drain to do it; the integer drain method doesn't give the fluid handler the instructions it needs to grab the right fluid type. Should be an easy fix.

**Comment by MercuriusXeno** [comment]
Tested it out, should be fixed in next build.
