### ISSUE TITLE
Crystallize Goo

### ISSUE THREAD

**Issue by MercuriusXeno** [MercuriusXeno/Goo#51]
Similar to Essentia crystallization but less unitary.

Would like to be able to crystallize goo in increments of powers of 10.
(1, 10, 100, 1000, 10000, think I'd stop at ^5? ^7?) allowing you to store goo as chunky crystal items.
This would make it easier to isolate and automate specific goo types and work out ratio bottlenecks with more factorization.

Concept: put a quartz crystal inside a bulb by right clicking, the quartz crystal in the bulb will absorb the most prominent goo inside and grow (speed at which it increases in size is configurable). Right clicking with a crystal in the bulb will remove the crystal from the bulb at its current size and reverse any progress toward the next step (so it doesn't lose goo).

**Comment by MercuriusXeno** [comment]
Other uses for crystals include:
Beneficial player edible, like Goo Candy sort of. MOSTLY beneficial anyway. You shouldn't eat decay.

Ammunition for mid to late game mechanics that aren't strictly powered by liquid goo.

Refractor crystal for some kind of goo laser.

Crafting ingredient for goo-themed tools and objects.

**Comment by MercuriusXeno** [comment]
This is done - we'll get to features this unlocks TBD

**Comment by CoruscareGames** [comment]
Is there a recipe yet? How would this be made in the latest 1.16.1 version?

**Comment by MercuriusXeno** [comment]
It's documented in the bulb entry in the Patchouli book. Put a piece of quartz in a bulb with goo in it.

**Comment by MercuriusXeno** [comment]
I realize this is a bad place for the entry - I'll give them their own page in the next patch. Creating a new issue.
