### ISSUE TITLE
Crucibles don't accept goo

### ISSUE THREAD

**Issue by jackhardwareltd** [MercuriusXeno/Goo#58]
This related error was in the log: https://pastebin.com/58n4Fcfd

Crucibles don't accept goo from any direction. I was using plant goo specifically in this case. This is in version 1.16.1-0.6.2.7. (edit: and 0.6.3.5)

**Comment by jackhardwareltd** [comment]
I think the problem is that `updateFluidsTo` tries to `setGoo(fluids.get(0))` without checking if `fluids.get(0)` exists first.

I'll eventually get a Forge environment set up so I can directly help instead of opening a bunch of issues :)

**Comment by MercuriusXeno** [comment]
Fixed already.
