### ISSUE TITLE
"Errors in currently selected datapacks..."

### ISSUE THREAD

**Issue by Darkfiend009** [MercuriusXeno/Goo#6]
Minecraft: 1.16.1
Forge. 32.0.108
Goo: 0.5.3.2b
![image](https://user-images.githubusercontent.com/42146629/91182004-9a477780-e6b7-11ea-8843-b3f0e0f37395.png)

I tried creating a single player world with Goo to makes sure i could add it to a modpack. When trying to generate a new world, the above message is received. I did not change any single player world settings. Clicking Safe Mode does nothing. When i remove Goo from the modpack, a world generates without error.

**Comment by MercuriusXeno** [comment]
Noted. I'm still working through some major revisions under the hood and probably this error will end up being obviated by the work being done; I'll release a formal update once I have something worth showing.

**Comment by MercuriusXeno** [comment]
Try the latest on 0.5.6.2, with its relevant new dependencies: Aequivaleo (0.0.42 is what's required at the time of writing this but be aware it may bump up) and Patchouli 1.16-39 (again, may bump up, but not as likely to)

SHOULD be able to load; if not, we'll pick it up from scratch.

**Comment by MercuriusXeno** [comment]
As far as I know we're way past this. I'm gonna go ahead and close this.
