### ISSUE TITLE
[1.16.3] Invisible goop info in tooltip

### ISSUE THREAD

**Issue by Mike-U5** [MercuriusXeno/Goo#61]
The goop display in tooltips appears to be invisible. I can only see the "Item has no goop" message on some items. Modlist:
* Patchouli-1.16.2-44
* Goo+1.16.3-0.7.3.5
* aequivaleo-0.0.101-ALPHA-universal

![EmptyTooltip](https://user-images.githubusercontent.com/32613991/95675962-358aa280-0bbb-11eb-9384-a1020eb64de2.png)

**Edit:** Issue persists on Goo 1.16.3-0.7.3.7.

**Comment by MercuriusXeno** [comment]
You need to update your forge to 34.1.12 or greater, it's a forge bug. They were missing a tooltip event/drawing hook.
