### ISSUE TITLE
crash when using a lobber with metallic or royal goo

### ISSUE THREAD

**Issue by lag42** [MercuriusXeno/Goo#62]
hate to report this so early after you had an upload, but you uploaded that just as i was discovering this and it happened with the new version too
[crash report](https://gist.github.com/lag42/1abf3714a23d4ec3766b015963094b43)

versions:
minecraft: 1.16.3
forge: 34.1.19
aequivaleo: 0.0.105-ALPHA-universal
patchouli: 1.16.2-44
goo: 1.16.3-0.7.5.1

**Comment by MercuriusXeno** [comment]
I think I know what caused it.
```
                Optional<Entity> optionalOwner = Optional.empty();
                if (context.splat().owner() != null) {
                    Optional.of(context.splat().owner());
                }
                GooBlob returnBlob = new GooBlob(Registry.GOO_BLOB.get(), context.world(), optionalOwner,
                        new FluidStack(context.fluid(), amountReturned), dropPos);```

**Comment by MercuriusXeno** [comment]
Needs to properly create an optional instead of passing null into an optional, dumb mistake.

**Comment by MercuriusXeno** [comment]
This will get fixed next build
