### ISSUE TITLE
Server crash when placing goo in world

### ISSUE THREAD

**Issue by darkphan** [MercuriusXeno/Goo#63]
Minecraft: 1.16.3
Goo Version: 1.16.3 - 0.7.5.2
aequivaleo Version: 0.0.105-ALPHA
Forge: 34.1.19

When placing goo in the world on a server it crashes the server:

Crash Report: https://gist.github.com/darkphan/404bdcaa3d6edad69bd7976ac8702132

**Comment by MercuriusXeno** [comment]
Should be fixed in 6.5.4 and 7.5.4, and enjoyed the stream! Thanks!
