### ISSUE TITLE
most items are no longer goo

### ISSUE THREAD

**Issue by lag42** [MercuriusXeno/Goo#72]
some weirdness has happened with goo values, [several items have been declared not goo when it seems like they should be](https://imgur.com/a/qzCVSzo), it's also not just hidden, the gooifier will refuse to melt them

versions:
minecraft: 1.16.3
forge: 34.1.19
aequivaleo: 0.0.105-ALPHA-universal
patchouli: 1.16.2-44
goo: 1.16.3-0.7.5.5

**Comment by MercuriusXeno** [comment]
Probably an Aequivaleo issue; there has been a lot of backend work very recently to correct a variety of problems. Orion may have some answers, but it's possible that newer Aequivaleo builds have already addressed them. I'll keep an eye on it so we can check again in a later build.

**Comment by OrionDevelopment** [comment]
A PR needs to be merged into Aequivaleo: ldtteam/Aequivaleo#7 needs to be merged to gain improvements on this front.

**Comment by OrionDevelopment** [comment]
Transfered to ldtteam/Aequivaleo#8
