### ISSUE TITLE
dependency bug

### ISSUE THREAD

**Issue by BasiliskL** [MercuriusXeno/Goo#79]
i just tried using this mod and the twich loader started minecraft but it didn't finish because it said I didn't have the required dependencies for goo saying goo required aequivaleo version 0.0.105 and i had version 0.0.110 and that patchouli had to be version 44 not the recent version 45 update

**Comment by MercuriusXeno** [comment]
This is already fixed in a later build but it's not ready for release, sorry. I'll leave this open but for the current stable releases on CF, the dependency reqs are strict. In future releases they will allow for minimum version or higher.

**Comment by MercuriusXeno** [comment]
Sound be resolved in latest!
