### ISSUE TITLE
Cheap higher level items

### ISSUE THREAD

**Issue by AlexandrusConstantus** [MercuriusXeno/Goo#85]
Compound items of any kind, e.g. Goo Crucible:
Price from parts:
2* Iron bars : 27 Metal
3*Netherite Scrap: 960 Metal+120 Obsidian
Cauldron: 504 Metal
2*Blast Furnace: 360 Metal
Goo Bulb: 60 Weird

Sum: 3798 Metal, 360 Obsidian, 60 Weird

Price alone: 
2880 Metal
360 Obsidian

This isn't the worst, a 64k Storage Disk from Refined Storage sells for 45 Logic. It seems that the calculation leaves out significant parts of the recipes for accumulated costs. But as such, most items are far to cheap for my taste.

Setup:
Minecraft 1.16.3, Forge: 34.1.25, 
Modlist:
aequivaleo-0.0.111-ALPHA-universal
ceramicbucket-2.2.0-1.16.2+
chunkloaders-1.1.0-mc1.16.3
ExtraStorage-1.16.3-1.1.0
Goo-1.16.3-0.7.6.12
jei-1.16.3-7.6.0.49
Patchouli-1.16.2-47
planttech2-0.02.20
refinedstorage-1.9.7
refinedstorageaddons-0.7.2
SolarFluxReborn-1.16.3-16.2.3
Xaeros_Minimap_20.25.1_Forge_1.16.3
XaerosWorldMap_1.11.0_Forge_1.16.3

**Comment by OrionDevelopment** [comment]
It is known
Aequivaleo which is the underlying engine is still going through hefty development and performance changes.

In its current state it is configured by Goo to treat all unknown values as 0 which causes some items to be very cheap, while others are really expensive, especially modded items.

**Comment by MercuriusXeno** [comment]
Based on what Orion's told me, a fix for this is premature because the cycle-based implementation of Aequivaleo removes what would fix this. Holding out for changes.

**Comment by MercuriusXeno** [comment]
For what it's worth, I knew about this and forgot to document it because I assumed it was exclusively Aequivaleo's responsibility to manifest correct values. For instance, the goo bulbs don't seem to realize they have glass and gaskets in them, and show up as only weird goo (from the ender pearls) - so it happens on quite a few things with seemingly arbitrary outputs.

**Comment by AlexandrusConstantus** [comment]
It might be better if in this case, the item would get no goo value. At least it wouldn't break too much then.

**Comment by MercuriusXeno** [comment]
I'm going to wait for a more robust fix from Aequivaleo, is what I'm getting at.

**Comment by MercuriusXeno** [comment]
This should be fixed in the latest.
