### ISSUE TITLE
Goo/Patchouli interaction crash

### ISSUE THREAD

**Issue by Allyraya** [MercuriusXeno/Goo#87]
According to my sources the issue lies with the Goo mod. The issue is that whenever anyone on the server attempts to open a guide book, be it from Botania, Ars Nouveau, Nature's Aura, Industrial Foregoing, etc, the game immediately crashes to desktop.

**Comment by Entoarox** [comment]
It would help if you provide a log, since there is very little that can be done without one.

**Comment by MercuriusXeno** [comment]
FC1 is running every single one of those mods and goo and this is the first I've heard of it, so I'm skeptical. Let's see a crash log, please.

**Comment by Allyraya** [comment]
[crash-2020-11-02_21.40.29-client.txt](https://github.com/MercuriusXeno/Goo/files/5478983/crash-2020-11-02_21.40.29-client.txt)

**Comment by MercuriusXeno** [comment]
I'm not seeing anything in the crash log to indicate it's Goo. So I started up a server and connected to it as a client, and gave myself a book, and right clicked with it. It opens just fine.

What's the source's test criteria to inform them this is Goo's crash?

**Comment by Allyraya** [comment]
any guide book causes the crash. Attached is the log from trying to open the Goo and You guide book.
[crash-2020-11-03_08.25.47-client.txt](https://github.com/MercuriusXeno/Goo/files/5481439/crash-2020-11-03_08.25.47-client.txt)

**Comment by OrionDevelopment** [comment]
@Allyraya Could you please remove goo from your pack and try again?

**Comment by Allyraya** [comment]
[crash-2020-11-03_12.44.37-client.txt](https://github.com/MercuriusXeno/Goo/files/5483059/crash-2020-11-03_12.44.37-client.txt)
I did not assemble the pack, but I have tried to do as you asked. I had to load a single player world, so I do not know if it worked or not.

**Comment by Entoarox** [comment]
@Allyraya Yeah, log shows Goo is gone, so whatever is causing the issue, it aint Goo that does it....

**Comment by Allyraya** [comment]
Alright, thanks for the assistance, I will let the modpack curator know. :)

**Comment by raziel23x** [comment]
me and @valkrieofnight already aware if this @Allyraya

**Comment by MercuriusXeno** [comment]
Thank you guys; I'll close this, for now. Feel free to let us know if we need to revisit.
